<?php

class Form {
  
  protected $errors = array();
  protected $rules = array(
    "required",
    "string",
    "email",
    "url",
    "int",
    "date",
    "max",
    "min",
    "honeyPotValue",
    "honeyPotMicrotime",
    "confirmed",
    "csrf_token",
    "file_format",
    "file_maxsize_total",
  );
  protected $formName = '';
  protected static $csrf_token = '';
  
  public function validate($formName, $rules) {

    $this->formName = $formName;

    $request = $_REQUEST;
    $files = $_FILES;

    foreach ($rules as $ruleKey => $rule) {

      if (isset($request[$ruleKey]) || isset($files[$ruleKey])) {
        
        if (isset($request[$ruleKey])) {
          $this->addOld($ruleKey, $request[$ruleKey]); 
        }
        
        foreach ($rule['rules'] as $ruleItemKey => $ruleItem) {
          if (strpos($ruleItem, ':') !== false) {
            $ruleItemArr = explode(':', $ruleItem);
            if (in_array($ruleItemArr[0], $this->rules)) {
              if (strpos($ruleItemArr[0], 'file') !== false) {
                $this->{$ruleItemArr[0]}($ruleKey, $rule['alias'], $files[$ruleKey], $ruleItemArr[1]);
              } else {
                $this->{$ruleItemArr[0]}($ruleKey, $rule['alias'], $request[$ruleKey], $ruleItemArr[1]);
              }
            }
          } else {
            if (in_array($ruleItem, $this->rules)) {
              if ($ruleItem == 'confirmed') {
                $this->{$ruleItem}($ruleKey, $rule['alias'], $request);
              } else {
                if (strpos($ruleItem, 'file') !== false) {
                  $this->{$ruleItem}($ruleKey, $rule['alias'], $files[$ruleKey]);
                } else {
                  $this->{$ruleItem}($ruleKey, $rule['alias'], $request[$ruleKey]);
                }
              }
            }
          }
        }
        
      }
    }

    $this->storeErrors();

    if (empty($this->errors)) {
      $this->storeSuccess();
      return true;
    } else {
      return false;
    }
  }
  
  //Cross Site Request Forgery Prevention
  public static function getCSRFToken() {
    if(session_status() !== PHP_SESSION_ACTIVE)  {
      session_start();
    }
    if (empty(self::$csrf_token)) {
      self::newCSRFToken();
      return $_SESSION['csrf_token'];
    }
    return self::$csrf_token;  
  }

  //CSRF Token Generation
  public static function newCSRFToken() {
    if(session_status() !== PHP_SESSION_ACTIVE)  {
      session_start();
    }
    self::$csrf_token = bin2hex(random_bytes(32));
    $_SESSION['csrf_token'] = self::$csrf_token;
    return $_SESSION['csrf_token'];   
  }
  
  //CSRF Token Verification
  //The field being checked should have value generated by newCSRFToken()
  protected function csrf_token($field, $alias, $value) {
    if (!hash_equals($_SESSION['csrf_token'], $value)) {
      $errorTxt = \Lang\Dictionary::get('validation_error_csrf');
      $this->addError($field, $errorTxt, $value);
    }
  }
  
  protected function addOld($field, $value) {
    if(session_status() !== PHP_SESSION_ACTIVE)  {
      session_start();
    }
    $_SESSION['form_filled'][$field] = $value;
  }
  
  public static function getOld($field) {
    if(session_status() !== PHP_SESSION_ACTIVE)  {
      session_start();
    }
    if (isset($_SESSION['form_filled'][$field])) {
      return $_SESSION['form_filled'][$field];
    } else {
      return '';
    }  
  }
  
  protected function addError($field, $error, $value) {
    $error = ucfirst(mb_convert_case($error, MB_CASE_LOWER));
    if (isset($this->errors[$field])) {
      array_push($this->errors[$field]['errors'], $error);
    } else {
      $this->errors[$field]['value']  = $value;
      $this->errors[$field]['errors'][0] = $error;
    }
  }
  
  protected function storeErrors() {
    if(session_status() !== PHP_SESSION_ACTIVE)  {
      session_start();
    }
    
    $_SESSION['form_errors'][$this->formName] = $this->errors;
  }

  public static function addMainError($formName, $errorMsg) {
    $_SESSION['form_errors'][$formName]['form'] = $errorMsg;
  }

  protected function storeSuccess() {
    if(session_status() !== PHP_SESSION_ACTIVE)  {
      session_start();
    }

    $_SESSION['form_success'] = true;
  }
  
  public static function getFormErrors($formName = null) {
    if(session_status() !== PHP_SESSION_ACTIVE)  {
      session_start();
    }
    
    if (isset($_SESSION['form_errors'])) {
      if (exists($formName)) {
        return $_SESSION['form_errors'][$formName];
      } else {
        return $_SESSION['form_errors'];
      }      
    } else {
      return array();
    }    
  }
  
  public static function formSuccess() {
    if(session_status() !== PHP_SESSION_ACTIVE)  {
      session_start();
    }
    
    if (isset($_SESSION['form_success'])) {
      return true;
    } else {
      return false;
    }
  }

  public static function clear() {
    if(session_status() !== PHP_SESSION_ACTIVE)  {
      session_start();
    }

    if (isset($_SESSION['form_errors'])) {
      unset($_SESSION['form_errors']);
    }
    
    if (isset($_SESSION['form_success'])) {
      unset($_SESSION['form_success']);
    }
  }
  
  protected function required($field, $alias, $value) {
    if (empty($value)) {
      $errorTxt = \Lang\Dictionary::get('validation_error_required');
      $errorTxt = str_replace('#field#', $alias, $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }
  }
  
  protected function string($field, $alias, $value) {
    if ($value != '' && !is_string($value)) {
      $errorTxt = \Lang\Dictionary::get('validation_error_string');
      $errorTxt = str_replace('#field#', $alias, $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }
  }
  
  protected function email($field, $alias, $value) {
    if ($value != '' && filter_var($value, FILTER_VALIDATE_EMAIL) === false) {
      $errorTxt = \Lang\Dictionary::get('validation_error_email');
      $errorTxt = str_replace('#field#', $alias, $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }
  }
  
  protected function url($field, $alias, $value) {
    if ($value != '' && filter_var($value, FILTER_VALIDATE_URL) === false) {
      $errorTxt = \Lang\Dictionary::get('validation_error_url');
      $errorTxt = str_replace('#field#', $alias, $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }
  }
  
  protected function int($field, $alias, $value) {   
    if ($value != '' && filter_var($value, FILTER_VALIDATE_INT) === false) {
      $errorTxt = \Lang\Dictionary::get('validation_error_int');
      $errorTxt = str_replace('#field#', $alias, $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }
  }

  protected function date($field, $alias, $value) {
    $invalid = false;
    $dtPattern = '/^\d{4}-\d{2}-\d{2}$/mD';  

    if ($value != '' && !preg_match($dtPattern, $value)) {
      $invalid = true;
    } elseif($value == '') {

    } else {
      //Check if month and day are valid values...
      $year = substr($value, 0, 4);
      $month = (int) substr($value, 5, 2);
      $day = (int) substr($value, 8, 2);

      if ($month > 12 || $month < 1) {
        $invalid = true;
      }

      $gapYear = false;
      if ($year%4 == 0) {
        $gapYear = true;
      }

      if ($month == 2 && $gapYear) {
        $dayMax = 29;
      } elseif($month == 2 && !$gapYear) {
        $dayMax = 28;
      } elseif(in_array($month, array(1, 3, 5, 7, 8, 10, 12))) {
        $dayMax = 31;
      } else {
        $dayMax = 30;
      }

      if ($day > $dayMax || $day < 1) {
        $invalid = true;
      }
    }

    if ($invalid) {
      $errorTxt = \Lang\Dictionary::get('validation_error_date');
      $errorTxt = str_replace('#field#', $alias, $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }
  }
  
  protected function min($field, $alias, $value, int $min) {
    if ($value != '' && strlen($value) < $min) {
      $errorTxt = \Lang\Dictionary::get('validation_error_min');
      $errorTxt = str_replace(array('#field#', '#min#'), array($alias, $min), $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }
  }
  
  protected function max($field, $alias, $value, int $max) {
    if ($value != '' && strlen($value) > $max) {
      $errorTxt = \Lang\Dictionary::get('validation_error_max');
      $errorTxt = str_replace(array('#field#', '#max#'), array($alias, $max), $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }
  }

  protected function file_format($field, $alias, $value, $formats) {
    $formats = explode(',', $formats);
    
    if (exists($value['name']) && is_array($value['name'])) {
      //Multiple
      $allowed = true;
      foreach ($value['name'] as $fileKey => $fileName) {
        if(exists($fileName)) {
          $mimeExtension = \File\File::realFormat($value['tmp_name'][$fileKey]);
          $fileExtension = explode('.',$fileName);
          $fileExtension = strtolower(end($fileExtension));
          if (!\File\File::isAllowedFormat($fileExtension, $formats) || !\File\File::isAllowedFormat($mimeExtension, $formats)) {
            $allowed = false;
          }
        }
      }
    } else {
      //Single
      if(exists($value['name'])) {
        $mimeExtension = \File\File::realFormat($value['tmp_name']);
        $fileExtension = strtolower(end(explode('.',$value['name'])));
        if (!\File\File::isAllowedFormat($fileExtension, $formats) || !\File\File::isAllowedFormat($mimeExtension, $formats)) {
          $allowed = false;
        }
      }
    }
    
    if (!$allowed) {
      $errorTxt = \Lang\Dictionary::get('validation_error_file_format');
      $allowedFormatsTxt = implode(', ', $formats);
      $errorTxt = str_replace(array('#field#', '#formats#'), array($alias, $allowedFormatsTxt), $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }
  }

  protected function file_maxsize_total($field, $alias, $value, $maxSize) {
    $totalSize = 0;

    $allowed = true;
    if (is_array($value['name'])) {
      //Multiple   
      foreach ($value['size'] as $fileKey => $fileSize) {
        $totalSize += $fileSize;
        if ($totalSize > $maxSize) {
          $allowed = false;
        }
      }
    } else {
      //Single
      if ($value['size']  > $maxSize) {
        $allowed = false;
      }
    }

    if (!$allowed) {
      $errorTxt = \Lang\Dictionary::get('validation_error_file_maxsize_total');
      $errorTxt = str_replace('#field#', $alias, $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }

  }

  protected function file_maxsize_every($field, $alias, $value, $maxSize) {

    $oversized = 0;
    if (is_array($value['name'])) {
      //Multiple   
      foreach ($value['size'] as $fileKey => $fileSize) {
        if ($fileSize > $maxSize) {
          $oversized++;
        }
      }
    } else {
      //Single
      if ($value['size'] > $maxSize) {
        $oversized++;
      }
    }

    if ($oversized) {
      $errorTxt = \Lang\Dictionary::get('validation_error_file_maxsize_every');
      $errorTxt = str_replace(array('#field#', '#qty#'), array($alias, $oversized), $errorTxt);
      $this->addError($field, $errorTxt, $value);
    }

  }
  
  //HoneyPot
  protected function honeyPotValue($field, $alias, $value) {
    if ($value != '') {
      //Filled a field that is hidden to users 
      //and with a previous message for blind people and such
      //Probably a bot...
      $errorTxt = \Lang\Dictionary::get('validation_error_honeyPot');
      $this->addError($field, $errorTxt, $value);
    }
  }
  
  protected function honeyPotMicrotime($field, $alias, $value) {    
    $now = microtime(true);
    if (empty($value)) {
      $value = $now;
    }
    if (($now - $value) < 4) {
      //Failed time check, too quick to be a user...
      //Probably a bot...
      $errorTxt = \Lang\Dictionary::get('validation_error_honeyPot');
      $this->addError($field, $errorTxt, $value);
    }
  }
  
  //Confirmation
  //Repeat password and stuff like that...
  protected function confirmed($field, $alias, $values) {
    $confirmationSuffix = '_confirmation';
    if (isset($values[$field.$confirmationSuffix])) {
      if ($values[$field] == $values[$field.$confirmationSuffix]) {
      } else {
        $errorTxt = \Lang\Dictionary::get('validation_error_confirmed_nomatch');
        $errorTxt = str_replace('#field#', $alias, $errorTxt);
        $this->addError($field, $errorTxt, $values[$field]);
      }
    } else {      
      $errorTxt = \Lang\Dictionary::get('validation_error_confirmed_notset');
      $errorTxt = str_replace('#field#', $alias, $errorTxt);
      $this->addError($field, $errorTxt, $values[$field]);
    }
  }
  
}